int vorks;
int rpoc;
int depth = 100;
float r = 300;
float a = 1;
float b = 1;
float n1 = 1;
float n2 = 1;
float n3 = 1;
float m = 0;
float a1 = 1;
float b1 = 1;
float n11 = 1;
float n21 = 1;
float n31 = 1;
float m1 = 0;
float offset = 0;
float an1 = -PI;
float an2 = PI;
float an3 = -HALF_PI;
float an4 = HALF_PI;
int mxm = 1;
int mfs = 0;
PVector[][] globe;
int rms = 2;
int rms1 = 0;
PeasyCam cam;
PMatrix3D currCameraMatrix;
PGraphics3D g3;
ControlP5 MyController;
int ON_OF = 0;
int gm = 0;
String main;
int ggg;
int iii;
String mainn;
int gggg;
int iiii;
int rmm = 0;
int dec = 0;
int ui3d = 0;
int zx = 0;
int av = 0;
float afset;
float ofset;
float AXM1 = 0.01;
float AXXM = 0.01;
float RAXM = 5;
float RAM1 = 5;
float aafset;
float oofset;
int mxr = 0;
int rmss,rmss1,gm1,mfs1,mxm1;
int lolo=0;
int rmbd=0;
int soc;
int saveobj = 0;
String revelo;
PFont mono;
int vam = 0;
int tanxx = 0;
int OC1;
int VAM;
int H = 125, S = 125 ,B = 125;
int gsoc;
int rops;
